<a href="https://colab.research.google.com/github/ce888-sr/CE888/blob/master/Lab4/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [227]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [228]:
# Load the data
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header=None)
test = df
test.head()

0      1      2      3      4    ...    96     97     98     99     100
0   74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1  100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2   49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3   48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4   91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60

[5 rows x 101 columns]

In [229]:
#replace the value 99 with NaN
test = test.replace(99, np.nan).copy()

In [230]:
#drop column 1 as it contains jokes not ratings
test = test.drop([0], axis=1).copy()

In [231]:
test

1     2     3     4     5     6    ...   95    96    97    98    99    100
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4      8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  0.44  7.43  9.08  2.33  3.20  6.75  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  9.13 -8.16  8.59  9.08  0.87 -8.93  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   NaN   NaN   NaN   NaN -7.77   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   NaN   NaN   NaN   NaN -9.71   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 100 columns]

In [232]:
max_value = test.max()
print('Maximum value in each column : ')
print(max_value)

Maximum value in each column : 
1      9.37
2      9.37
3      9.37
4      9.37
5      9.37
       ... 
96     9.37
97     9.37
98     9.37
99     9.37
100    9.37
Length: 100, dtype: float64


In [ ]:
min_value = test.min()
print('Minimum value in each column : ')
print(min_value)

Minimum value in each column : 
1     -9.95
2     -9.95
3     -9.95
4     -9.95
5     -9.95
       ... 
96    -9.95
97    -9.95
98    -9.95
99    -9.95
100   -9.95
Length: 100, dtype: float64


In [233]:
new_df = test.mean(axis=0, skipna=True)

In [234]:
new_df

1      0.904573
2      0.208460
3      0.316574
4     -1.449114
5      0.403556
         ...   
96     1.528003
97     1.673750
98     0.767692
99    -0.031244
100    1.354711
Length: 100, dtype: float64

In [235]:
new_df.idxmin()

58

In [236]:
new_df.min()

-3.8338796373689923

In [237]:
new_df.idxmax()

50

In [238]:
new_df.max()

3.6650848950824937

In [239]:
low = test[33]
low.iloc[12215]

8.4

In [240]:
arr = test.values
print(arr.shape)

(24983, 100)


In [241]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2498300 (2498300,)


In [242]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [243]:
new_arr, idx = replace(arr, 0.1)

In [244]:
arr[idx[0][0], idx[1][0]]

2.09

In [245]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [246]:
n_latent_factors = 2

user_ratings = test.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [247]:
latent_item_features

array([[0.74803799, 0.28519648],
       [0.91092306, 0.54562993],
       [0.13076067, 0.99778934],
       [0.25324064, 0.03385297],
       [0.40377735, 0.33095199],
       [0.77917106, 0.62814212],
       [0.21777622, 0.75101955],
       [0.86261441, 0.30599746],
       [0.86178223, 0.93821375],
       [0.33882551, 0.7563249 ],
       [0.36143422, 0.90960154],
       [0.69534412, 0.54919489],
       [0.23940537, 0.0179419 ],
       [0.08090349, 0.43128636],
       [0.53472299, 0.35476048],
       [0.38000496, 0.07464567],
       [0.82508887, 0.60015225],
       [0.63738121, 0.57529157],
       [0.70492386, 0.87505345],
       [0.74454331, 0.61523149],
       [0.24891623, 0.92452006],
       [0.4814712 , 0.76940927],
       [0.09712911, 0.49243872],
       [0.77030681, 0.00778683],
       [0.96394196, 0.18104038],
       [0.05986833, 0.98874617],
       [0.60273195, 0.13046298],
       [0.83501026, 0.59250088],
       [0.27138629, 0.89467039],
       [0.02896734, 0.41267757],
       [0.

In [248]:
latent_user_preferences

array([[0.99015104, 0.08269612],
       [0.08650391, 0.99929999],
       [0.30832008, 0.77098441],
       ...,
       [0.88593268, 0.92358794],
       [0.24718752, 0.71177504],
       [0.34119215, 0.26759975]])

In [249]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        #if (iteration % 100) == 0:
        print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
        mse_history.append(mse)
    return mse_history      

In [ ]:
#sgd(2)

In [ ]:
num_iter = 20
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
#plt.figure()
#plt.plot(np.arange(0, num_iter, 10), hist)
#plt.xlabel("Iterations")
#plt.ylabel("MSE")
#plt.show()


Iteration 0/20:	MSE=26.205003
Iteration 1/20:	MSE=25.246806
Iteration 2/20:	MSE=24.954144
Iteration 3/20:	MSE=24.718394
Iteration 4/20:	MSE=24.486006
Iteration 5/20:	MSE=24.250867
Iteration 6/20:	MSE=24.013082
Iteration 7/20:	MSE=23.774038
Iteration 8/20:	MSE=23.535439
Iteration 9/20:	MSE=23.299003
Iteration 10/20:	MSE=23.066308
Iteration 11/20:	MSE=22.838671
Iteration 12/20:	MSE=22.617048
Iteration 13/20:	MSE=22.401941
Iteration 14/20:	MSE=22.193308
Iteration 15/20:	MSE=21.990473
Iteration 16/20:	MSE=21.792041
Iteration 17/20:	MSE=21.595817
Iteration 18/20:	MSE=21.398748
Iteration 19/20:	MSE=21.196938


In [250]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[0.76425524, 0.94707289, 0.21198612, ..., 0.45839277, 0.63174695,
        0.4448702 ],
       [0.34970505, 0.62404639, 1.00840218, ..., 0.22438629, 0.25162548,
        0.21886601],
       [0.45051718, 0.70152804, 0.80959617, ..., 0.28121062, 0.34427586,
        0.27374055],
       ...,
       [0.92611534, 1.31095373, 1.03739135, ..., 0.56800943, 0.73347448,
        0.55219442],
       [0.38790139, 0.61353458, 0.74252395, ..., 0.24285607, 0.29455874,
        0.23645752],
       [0.3315432 , 0.45681023, 0.31162269, ..., 0.20238398, 0.26503427,
        0.19667856]])

In [251]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = test.columns

In [252]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

1    ...                          100
0      (-7.82, 0.7642552398290778)  ...   (nan, 0.44487019608650324)
1      (4.08, 0.34970505338176455)  ...  (1.07, 0.21886600984199017)
2       (nan, 0.45051717833019134)  ...    (nan, 0.2737405523503542)
3       (nan, 0.46364582895981293)  ...    (nan, 0.2813396246310406)
4        (8.5, 0.6895975148168411)  ...   (1.6, 0.40613536042440795)
...                            ...  ...                          ...
24978    (0.44, 0.801714901039484)  ...  (7.43, 0.47121735838546763)
24979   (9.13, 0.5270744769245882)  ...   (8.45, 0.3182206745671918)
24980    (nan, 0.9261153356726225)  ...     (nan, 0.552194422605711)
24981    (nan, 0.3879013943475558)  ...    (nan, 0.2364575172773358)
24982  (2.43, 0.33154320066074716)  ...   (nan, 0.19667855931500905)

[24983 rows x 100 columns]

In [253]:
predict_rating(12435, 55)

0.1747607998110263

In [ ]:
# Load movies data
item_features_df = pd.read_excel('/content/movies_latent_factors.xlsx', sheet_name='Items')
item_features_df.head()

Movie ID  ...  Factor15
0        11  ... -0.248806
1        12  ...  1.274993
2        13  ... -0.419092
3        14  ... -0.681191
4        22  ... -2.292566

[5 rows x 17 columns]

In [ ]:
# Load movies data
user_features_df = pd.read_excel('/content/movies_latent_factors.xlsx', sheet_name='Users')
user_features_df.head()

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0  4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1   156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2  5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3   174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4  4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669

[5 rows x 16 columns]

In [ ]:
user_features_df.loc[[3], ['Factor15']].head()

Factor15
3  0.050692

In [254]:
item_features_df.iloc[df1['Factor10'].idxmin()]


Movie ID               597
Title       Titanic (1997)
Factor1            1.56787
Factor2           -1.51695
Factor3           -2.52338
Factor4            1.20448
Factor5            1.72954
Factor6         -0.0889414
Factor7           0.102822
Factor8            1.74779
Factor9            1.81696
Factor10          -2.98681
Factor11         -0.589441
Factor12          -2.56858
Factor13          0.370387
Factor14           2.21593
Factor15          0.456127
key                      0
item_id                 47
Name: 47, dtype: object

In [255]:
n_latent_factors = 15

# Initialise as random values
latent_user_preferences = np.random.random((user_features_df.shape[0], n_latent_factors))
latent_item_features = np.random.random((item_features_df.shape[1], n_latent_factors))

In [256]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[4.74506228, 4.0097732 , 3.98492251, 3.82876086, 4.51231755,
        3.57212879, 4.04600222, 4.80145771, 5.60823088, 2.71747838,
        5.06059626, 4.23567278, 3.10651708, 5.34607167, 2.79313855,
        4.65641244, 4.31523439, 3.68079063, 3.72233449],
       [4.73616599, 4.51780389, 3.21695186, 4.16303745, 5.02292542,
        4.15178786, 3.4703416 , 4.80203969, 5.19133934, 2.61434471,
        4.37915633, 4.76127032, 3.18297787, 5.43414976, 3.13081307,
        4.45068399, 4.40330942, 3.05030664, 3.24857278],
       [2.93782295, 2.46929121, 2.45799875, 2.07535583, 3.18032109,
        2.388481  , 1.93397029, 2.51641665, 3.225503  , 2.20390472,
        3.04557878, 2.29589639, 1.78712723, 3.05451571, 1.90325823,
        2.62892907, 2.65149656, 2.59470573, 2.55215575],
       [3.04976653, 2.94108789, 2.710998  , 2.68764782, 3.08166819,
        2.95029983, 2.23564614, 3.2096391 , 4.10877604, 2.12185316,
        3.31224908, 3.37055565, 1.85781926, 3.75991991, 2.00315657,
        3.081

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = user_features_df.columns

In [ ]:
predict_rating(5338, 55)

User  ...                     user_id
0   (4768.0, 3.3658904299365635)  ...     (0.0, 4.63232473798693)
1    (156.0, 3.9641629752898937)  ...    (1.0, 4.695738307213197)
2    (5323.0, 3.318296069295528)  ...    (2.0, 4.809682738608731)
3    (174.0, 3.5267292984015746)  ...    (3.0, 4.476501475717788)
4   (4529.0, 2.6229189410675526)  ...   (4.0, 3.4253431003815793)
5    (783.0, 2.6774245239705925)  ...     (5.0, 3.98888761825627)
6   (3878.0, 2.9196301391871717)  ...    (6.0, 4.269471026622807)
7     (768.0, 3.011546404809141)  ...    (7.0, 3.613025853894832)
8   (4469.0, 3.3545632277931783)  ...    (8.0, 5.310032224455773)
9   (1882.0, 2.8603107710058593)  ...    (9.0, 4.076556685964033)
10   (4997.0, 2.338228978855855)  ...  (10.0, 3.7417864706215127)
11  (2067.0, 2.5322689386364545)  ...  (11.0, 3.7556502093670026)
12  (3806.0, 3.7764871038354366)  ...  (12.0, 5.4793109736401115)
13  (2848.0, 2.8286096726356327)  ...  (13.0, 3.5097016956198344)
14  (4433.0, 3.4711705980567684)  ...   (14.0, 4.637132928486627)
15   (3519.0, 3.045383521691764)  ...   (15.0, 4.337635941622171)
16   (5338.0, 3.019160906996098)  ...   (16.0, 4.873108374111058)
17  (3947.0, 3.0844955566919845)  ...   (17.0, 4.878026980577927)
18  (4373.0, 2.8994406705955846)  ...  (18.0, 3.5393272295109752)
19   (2092.0, 4.270625177419592)  ...    (19.0, 4.72785388545863)
20   (525.0, 3.4854673596302947)  ...   (20.0, 4.416216236692144)
21   (4327.0, 4.027666618582406)  ...   (21.0, 5.459484170472194)
22  (3048.0, 3.5170396758364015)  ...  (22.0, 4.5741455405209175)
23  (2665.0, 3.8059644785090447)  ...   (23.0, 4.728861810585613)
24  (4940.0, 2.3950359287810166)  ...  (24.0, 3.4302780779252076)

[25 rows x 18 columns]